---

- name: Install nginx
  apt: name=nginx state=present

- name: Make sure /var/www exist
  file: path=/var/www state=directory owner=www-data mode=0755

- name: Make sure index file exist
  template: src=var/www/index.html dest=/var/www/index.html owner=www-data mode=0600
  notify:
    - restart nginx

- name: Make sure default.conf is overrided
  template: src=etc/nginx/conf.d/default.conf dest=/etc/nginx/sites-enabled/default owner=root mode=0600
  notify:
    - restart nginx
